export class Lead {
    Lead_Id: number;
    Lead_Name: string;
    Phone: string;
    Source: number;
    Source_Name: string;
    POC_Full_Name: string;
    POC_Direct_Mobile: string;
    POC_Work_Phone: string;
    POC_Email: string;
    POC_Designation_Id: number;
    POC_Designation: string;
    POC_State_Id: number;
    POC_State: string;
    POC_Location_Id: number;
    POC_Loc: string;
    POC_Office_Type: string;
    Name_Captured: boolean;
    Number_Captured: boolean;
    Email_Captured: boolean;
    Vertical: string;        // comma-separated Vertical IDs e.g. "1,3"
    Vertical_Name: string;
    Enquiry_For: string;     // *-separated selected enquiry IDs
    Project_Name: string;
    Company_Size_Id: number;
    Company_Size_Name: string;
    Next_Call_Action: boolean;
    Address: string;
    State: number;
    State_Name: string;
    District: number;
    District_Name: string;
    Department_Id: number;
    Department_Name: string;
    Status_Id: number;
    Status_Name: string;
    Staff_Id: number;
    Staff_Name: string;
    Remark: string;
    Enquiry_For_Note: string;
    Next_FollowUp_Date: any;
    Remarks: string;
    Location_Id: number;
    Location_Name: string;
    Branch_Id: number;
    Branch_Name: string;
    Lead_Type: number;
    Is_FollowUp: boolean;
    FollowUp_Department_Id: number;
    FollowUp_Status_Id: number;
    FollowUp_Staff_Id: number;
    FollowUp_Staff_Name: string;
    FollowUp_Remark: string;
    FollowUp_Location_Id: number;
    FollowUp_Location_Name: string;
    FollowUp_Branch_Id: number;
    FollowUp_Branch_Name: string;
    FollowUp_Dept_Name: string;
    FollowUp_Status_Name: string;
    FollowUp_Date: string; // New Field for Date & Time
    Login_User_Id: number; // New Field for User ID
    FollowUp_Next_Date: any;
    Entry_Date: any;
    Lead_Priority: string;
    Contact_Person_Details: any[] = [];
    Last_FollowUp_Date: any;

    constructor() {
        this.Lead_Id = 0;
        this.Lead_Name = "";
        this.Phone = "";
        this.Source = 0;
        this.POC_Full_Name = "";
        this.POC_Direct_Mobile = "";
        this.POC_Work_Phone = "";
        this.POC_Email = "";
        this.POC_Designation_Id = 0;
        this.POC_Designation = "";
        this.POC_State_Id = 0;
        this.POC_State = "";
        this.POC_Location_Id = 0;
        this.POC_Loc = "";
        this.POC_Office_Type = "Head office";
        this.Name_Captured = false;
        this.Number_Captured = false;
        this.Email_Captured = false;
        this.Vertical = '';
        this.Enquiry_For = '';
        this.Project_Name = "";
        this.Company_Size_Id = 0;
        this.Next_Call_Action = false;
        this.Address = "";
        this.State = 0;
        this.District = 0;
        this.Department_Id = 0;
        this.Status_Id = 0;
        this.Staff_Id = 0;
        this.Remark = "";
        this.Location_Id = 0;
        this.Branch_Id = 0;
        this.Branch_Name = "";
        this.Lead_Type = 0;
        this.Is_FollowUp = false;
        this.FollowUp_Department_Id = 0;
        this.FollowUp_Status_Id = 0;
        this.FollowUp_Staff_Id = 0;
        this.FollowUp_Remark = "";
        this.FollowUp_Location_Id = 0;
        const d = new Date();
        const formattedDate = `${d.getFullYear()}-${('0' + (d.getMonth() + 1)).slice(-2)}-${('0' + d.getDate()).slice(-2)}`;
        this.Entry_Date = formattedDate;
        this.FollowUp_Next_Date = formattedDate;
        this.Lead_Priority = "Medium";
    }
}
