export class salesquotationmaster
{
SalesQuotationMaster_Id:number;
Account_Party_Id:number;
EntryDate:string;
SONo:string;
QuotationNo:string;
POnumber:string;
CurrencyId:number;
TypeId:number;
PaymentTerms:string;
AttendEmployee:string;
TotalAmount:number;
TotalDiscount:number;
TaxableAmount:number;
VatAmount:number;
Roundoff_Amt:number;
Total_Amount:number;
NetTotal:number;
Brand:string;
PriceBasis:string;
Delivery:string;
Validity:string;
Description1:string;
User_Id:number;
Delivery_Address1:string;
Delivery_Address2:string;
Delivery_Address3:string;
Delivery_Address4:string;
KindAttend:string;
Charge1:string;
charge1_Amount:number;
Charge2:string;
charge2_Amount:number;
Discount_Description:number;
Additional_Discount:number;
Description2:string;
Basic_Discount:string;
Amount_In_Words:string;
PreparedBy:string;
Charge1per:number;
Payment_Term_Description:number;
VAT_Description:string;
VAT_Percentage:number;
VAT_Amount:number;
SalesQuotation_Image:string;
Acknolodgement_Image:string;
CurrecnyName:string;
UserName:string;
constructor(values: Object = {})  
{
Object.assign(this, values) 
}
}

