var http = require('http');
var db = require("./dbconnection");

process.on('uncaughtException', (err) => {
  console.error('UNCAUGHT EXCEPTION! Shutting down...', err);
});

process.on('unhandledRejection', (reason, promise) => {
  console.error('UNHANDLED REJECTION! Shutting down...', reason);
});

const port = process.env.PORT || 3504;
var express = require("express");
var path = require("path");
var favicon = require("serve-favicon");
var multer = require('multer');
var multerupload = multer({ dest: 'fileprint/' })
var logger = require("morgan");
var cookieParser = require("cookie-parser");
var bodyParser = require("body-parser");
var cors = require("cors");
const jwt = require('./helpers//jwt');
var routes = require("./routes/index");
const errorHandler = require('./helpers/error-handler');
const requestContext = require("./helpers/request-context");
const autoResponseWrapper = require("./helpers/auto-response-wrapper");

var Login = require("./routes/Login");
var Account_Group = require('./routes/Account_Group');
var Account_Years = require('./routes/Account_Years');
var Accounts = require('./routes/Accounts');
var Brand = require('./routes/Brand');
var Client_Accounts = require('./routes/Client_Accounts');
var Company = require('./routes/Company');
var Contra_Entry = require('./routes/Contra_Entry');
var Country_Of_Orgin = require('./routes/Country_Of_Orgin');
var country = require('./routes/country');
var creditnote_details = require('./routes/creditnote_details');
var creditnote_master = require('./routes/creditnote_master');
var currencydetails = require('./routes/currencydetails');
var Dashboard = require('./routes/Dashboard');
var debitnote_details = require('./routes/debitnote_details');
var debitnote_master = require('./routes/debitnote_master');
var delivery_salesmaster = require('./routes/delivery_salesmaster');
var deliveryorderdetails = require('./routes/deliveryorderdetails');
var deliveryordermaster = require('./routes/deliveryordermaster');
var Employee_Details = require('./routes/Employee_Details');
var General_Settings = require('./routes/General_Settings');
var HSN = require('./routes/HSN');
var Item_Group = require('./routes/Item_Group');
var Item = require('./routes/Item');
var Model = require('./routes/Model');
var TermsAndCondition = require('./routes/TermsAndCondition');
var Journal_Entry = require('./routes/Journal_Entry');
var Menu = require('./routes/Menu');
var Payment_Reference = require('./routes/Payment_Reference');
var payment_term = require('./routes/payment_term');
var Payment_Voucher = require('./routes/Payment_Voucher');
var performa_delivery_order = require('./routes/performa_delivery_order');
var performa_salesmaster = require('./routes/performa_salesmaster');
var performainvoicedetails = require('./routes/performainvoicedetails');
var performainvoicemaster = require('./routes/performainvoicemaster');
var Primary_Details = require('./routes/Primary_Details');
var Proforma_Invoice_Master = require('./routes/Proforma_Invoice_Master');
var Purchase_Details = require('./routes/Purchase_Details');
var Purchase_Master = require('./routes/Purchase_Master');
var Purchase_Order_Master = require('./routes/Purchase_Order_Master');
var purchase_return_details = require('./routes/purchase_return_details');
var Purchase_Return_Master = require('./routes/Purchase_Return_Master');
var Purchase_Type = require('./routes/Purchase_Type');
var purchaseorder_purchasemaster = require('./routes/purchaseorder_purchasemaster');
var purchaseorderdetails = require('./routes/purchaseorderdetails');
var purchaseordermaster = require('./routes/purchaseordermaster');
var quotation_delivery_order = require('./routes/quotation_delivery_order');
var quotation_performa = require('./routes/quotation_performa');
var quotation_purchaseordermaster = require('./routes/quotation_purchaseordermaster');
var quotation_salesmaster = require('./routes/quotation_salesmaster');
var Receipt_Reference = require('./routes/Receipt_Reference');
var Receipt_Voucher = require('./routes/Receipt_Voucher');
var Sale_Unit = require('./routes/Sale_Unit');
var sales_delivery = require('./routes/sales_delivery');
var Sales_Details = require('./routes/Sales_Details');
var Sales_Master = require('./routes/Sales_Master');
var sales_quotation_order = require('./routes/sales_quotation_order');
var Sales_Return_Details = require('./routes/Sales_Return_Details');
var Sales_Return_Master = require('./routes/Sales_Return_Master');
var salesorderdetails = require('./routes/salesorderdetails');
var salesordermaster = require('./routes/salesordermaster');
var sales_order_master = require('./routes/sales_order_master');
var salesquotationdetails = require('./routes/salesquotationdetails');
var salesquotationmaster = require('./routes/salesquotationmaster');
var Stock_Add_Details = require('./routes/Stock_Add_Details');
var Stock_Add_Master = require('./routes/Stock_Add_Master');
var Stock_Details = require('./routes/Stock_Details');
var Stock = require('./routes/Stock');
var User_Details = require('./routes/User_Details');
var User_Menu_Selection = require('./routes/User_Menu_Selection');
var User_Type = require('./routes/User_Type');
var User_Role = require('./routes/User_Role');
var Working_Status = require('./routes/Working_Status');
var stock_take_name =  require('./routes/stock_take_name');
var Stock_Take_Master=require('./routes/Stock_Take_Master');
var Lead = require('./routes/Lead');
var LeadRequirement = require('./routes/LeadRequirement');
var requirementmaster = require('./routes/requirementmaster');
var requirementdetails = require('./routes/requirementdetails');
var requirementworkflow = require('./routes/requirementworkflow');
var Sales_Order_Master = require('./routes/sales_order_master');
var Vertical = require('./routes/Vertical');
var Designation = require('./routes/Designation');
var Company_Size = require('./routes/Company_Size');
var Department = require('./routes/Department');
var DepartmentStatus = require('./routes/DepartmentStatus');
var Price_Response = require('./routes/Price_Response');


var app = express();
var server = http.Server(app);

app.set("views", path.join(__dirname, "views"));
app.set("view engine", "jade");
app.use(cors({ origin: true, credentials: true }));
app.options('*', cors({ origin: true, credentials: true }));
app.use((req, res, next) => {
  if (req.method === 'OPTIONS') return res.sendStatus(200);
  next();
});
app.use(requestContext({ timeoutMs: Number(process.env.API_TIMEOUT_MS || 60000) }));
app.use(autoResponseWrapper());
app.use(logger("dev"));
app.use(bodyParser.json({ limit: "50mb" }));
app.use(bodyParser.urlencoded({ limit: "50mb", extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, "public")));
app.use("/", routes);
app.use("/Login", Login);
app.use(jwt());

app.use('/Account_Group',Account_Group);
app.use('/Account_Years',Account_Years);
app.use('/Accounts',Accounts);
app.use('/Brand',Brand);
app.use('/Client_Accounts',Client_Accounts);
app.use('/Company',Company);
app.use('/Contra_Entry',Contra_Entry);
app.use('/Country_Of_Orgin',Country_Of_Orgin);
app.use('/country',country);
app.use('/creditnote_details',creditnote_details);
app.use('/creditnote_master',creditnote_master);
app.use('/currencydetails',currencydetails);
app.use('/Dashboard',Dashboard);
app.use('/debitnote_details',debitnote_details);
app.use('/debitnote_master',debitnote_master);
app.use('/delivery_salesmaster',delivery_salesmaster);
app.use('/deliveryorderdetails',deliveryorderdetails);
app.use('/deliveryordermaster',deliveryordermaster);
app.use('/Employee_Details',Employee_Details);
app.use('/General_Settings',General_Settings);
app.use('/HSN',HSN);
app.use('/Item_Group',Item_Group);
app.use('/Item',Item);
app.use('/Model',Model);
app.use('/TermsAndCondition', TermsAndCondition);
app.use('/Journal_Entry',Journal_Entry);
app.use('/Menu',Menu);
app.use('/Payment_Reference',Payment_Reference);
app.use('/payment_term',payment_term);
app.use('/Payment_Voucher',Payment_Voucher);
app.use('/performa_delivery_order',performa_delivery_order);
app.use('/performa_salesmaster',performa_salesmaster);
app.use('/performainvoicedetails',performainvoicedetails);
app.use('/performainvoicemaster',performainvoicemaster);
app.use('/Primary_Details',Primary_Details);
app.use('/Proforma_Invoice_Master',Proforma_Invoice_Master);
app.use('/Purchase_Details',Purchase_Details);
app.use('/Purchase_Master',Purchase_Master);
app.use('/Purchase_Order_Master',Purchase_Order_Master);
app.use('/purchase_return_details',purchase_return_details);
app.use('/Purchase_Return_Master', Purchase_Return_Master);
app.use('/Purchase_Type',Purchase_Type);
app.use('/purchaseorder_purchasemaster',purchaseorder_purchasemaster);
app.use('/purchaseorderdetails',purchaseorderdetails);
app.use('/purchaseordermaster',purchaseordermaster);
app.use('/quotation_delivery_order',quotation_delivery_order);
app.use('/quotation_performa',quotation_performa);
app.use('/quotation_purchaseordermaster',quotation_purchaseordermaster);
app.use('/quotation_salesmaster',quotation_salesmaster);
app.use('/Receipt_Reference',Receipt_Reference);
app.use('/Receipt_Voucher',Receipt_Voucher);
app.use('/Sale_Unit',Sale_Unit);
app.use('/sales_delivery',sales_delivery);
app.use('/Sales_Details',Sales_Details);
app.use('/Sales_Master',Sales_Master);
app.use('/sales_quotation_order',sales_quotation_order);
app.use('/Sales_Return_Details',Sales_Return_Details);
app.use('/Sales_Return_Master',Sales_Return_Master);
app.use('/salesorderdetails',salesorderdetails);
app.use('/salesordermaster',salesordermaster);
app.use('/sales_order_master',sales_order_master);
app.use('/salesquotationdetails',salesquotationdetails);
app.use('/salesquotationmaster',salesquotationmaster);
app.use('/Stock_Add_Details',Stock_Add_Details);
app.use('/Stock_Add_Master',Stock_Add_Master);
app.use('/Stock_Details',Stock_Details);
app.use('/Stock',Stock);
app.use('/User_Details',User_Details);
app.use('/User_Menu_Selection',User_Menu_Selection);
app.use('/User_Type',User_Type);
app.use('/User_Role',User_Role);
app.use('/Working_Status',Working_Status);
app.use('/stock_take_name',stock_take_name);
app.use('/Stock_Take_Master',Stock_Take_Master);
app.use('/Lead', Lead);
app.use('/LeadRequirement', LeadRequirement);
app.use('/requirementmaster', requirementmaster);
app.use('/requirementdetails', requirementdetails);
app.use('/requirementworkflow', requirementworkflow);
app.use('/Sales_Order_Master', Sales_Order_Master);
app.use('/Vertical', Vertical);
app.use('/Designation', Designation);
app.use('/Company_Size', Company_Size);
app.use('/Department', Department);
app.use('/DepartmentStatus', DepartmentStatus);
app.use('/Price_Response', Price_Response);

app.use(errorHandler);

app.use(function(req, res, next) {
  var err = new Error("Not Found");
  err.status = 404;
  next(err); 
});

// app.listen(port, () => {
// 	console.log(`started on port: ${port}`);
//   });

app.get('Edabraod/', (req, res) => {
  res.send('Hello World!')
});

module.exports = app;
